### PR TITLE
I added my matzo ball recipe

### PR DESCRIPTION
**Pull request by jenniferabowd**
Enjoy! This recipe makes enough to feed a Hassidic family. That is not a joke.

### CODE REVIEW

**Review by sjsyrek — COMMENTED** [review]
This looks great. Can you put your name on it (as I did with my recipes) and link to it from the main README page?

**Comment by jenniferabowd** [comment]
Oh I'm so sorry about that! I made those changes!

**Comment by sjsyrek** [comment]
Don't be sorry, this is great. It's going in!

**Comment by jenniferabowd** [comment]
Yay! Thank you!

**Pull request merged**
